Feature/pipeline waves 274
aws-quickstart/ssp-amazon-eks pull request #286
Opened 2022-02-04 23:42 UTC by shapirov103

*Issue #, if available:* 274

*Description of changes:* Waves support with pipelines to deploy a group of clusters in parallel.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-02-04 23:46 UTC, shapirov103 commented
I ran preliminary tests. Functional test through codepipeline requires published artifact.

2022-02-04 23:50 UTC, shapirov103 commented
will merge the csi secrets first.

2022-02-04 23:56 UTC, shapirov103 commented
Please review just this commit: https://github.com/aws-quickstart/ssp-amazon-eks/pull/286/commits/6c624bb15f2c6f3370d5c99b415eafbff6a2e76e

2022-02-05 02:21 UTC, parkand1 requested changes
Left comments on the language but asides from that looks good to me

2022-02-06 02:48 UTC, askulkarni2 reviewed
It seems like code from Secrets Store CSI refactor is mixed in here (https://github.com/aws-quickstart/ssp-amazon-eks/commit/ce3bd6e0b308ef86cf5e893fab5f6917bf8755a2) is  mixed in here. Am I missing something?

2022-02-06 02:48 UTC, askulkarni2 commented on lib/pipelines/code-pipeline.ts
> +     * Waves for the pipe;ine. Stages inside the wave are executed in parallel.
Minor: typo pipe;ine

2022-02-07 15:10 UTC, shapirov103 commented
> It seems like code from Secrets Store CSI refactor is mixed in here ([ce3bd6e](https://github.com/aws-quickstart/ssp-amazon-eks/commit/ce3bd6e0b308ef86cf5e893fab5f6917bf8755a2)) is mixed in here. Am I missing something?

Yes, it is. I have branched off the argocd csi secrets branch, hoping these commits will not show up as they are part of the main already. See the PR description, I left a comment on it.

2022-02-07 15:28 UTC, shapirov103 commented
e2e succeeded. however, unsure why the PR is not showing it.

2022-02-07 18:59 UTC, askulkarni2 approved these changes
LGTM!

2022-02-07 21:25 UTC, youngjeong46 approved these changes
LGTM!

2022-02-09 04:37 UTC, parkand1 approved these changes
LGTM

2022-02-09 15:38 UTC, merged